---
# tasks file for mon_role_test
- name: Créer un fichier test
  ansible.builtin.file:        # ← utiliser le FQCN
    path: /tmp/fichier_test.txt
    state: touch
    mode: '0644'               # ← éviter risky permissions
- name: Dire que le fichier a été créé
  ansible.builtin.debug:
    msg: "Le fichier a été créé."
